import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";
import Footer from '@/components/shared/ui/footer';
import "./globals.css";
import Navbar from "@/components/shared/ui/navbar";

//const inter = Inter({ subsets: ["latin"] });

const displayFont = Syne({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-display',
});
  
const baseFont = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-default',
});

export const metadata: Metadata = {
  title: "Next template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`${baseFont.variable} ${displayFont.variable} scroll-smooth`}>
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  );
}
